# -*- coding: utf-8 -*-
"""E_Commerce_webscrap_(no_numbers)_Vader_ver.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i31NIOi_NNVuJte0dx3jqL035UfKcOhB
"""

# Downloading libraries for web-scraping
!pip install requests
!pip install beautifulsoup4==4.9.3
!pip install bs4
!pip install html5lib
!pip install num2words
!pip install vaderSentiment

# Importing libraries for web-scraping and tokenization purposes
from bs4 import BeautifulSoup as bs
import requests
import nltk
import pandas as pd
import re
from textblob import TextBlob
from num2words import num2words
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# The list of common words such as "a", "an", etc.
nltk.download('stopwords')
# Download a collection of popular resources from the NLTK library
nltk.download('popular', quiet=True)
# Sentence tokenization (Splitting a text into individual senteces)
nltk.download('punkt')
# English vocabulary database
nltk.download('wordnet')
# Used for training language models or evaluating nlp algothms
nltk.download('brown')
# Used for performing sentiment analysis on text
nltk.download('vader_lexicon')

from nltk.tokenize import sent_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
from nltk.tokenize import word_tokenize

lemmatizer = WordNetLemmatizer()
analyzer = SentimentIntensityAnalyzer()
stemmer = SnowballStemmer("english")
stop_words = stopwords.words("english")

sentences = []

def scrape_clean (url, div_class):
  # Load the website
  website = requests.get(url).text
  soup = bs(website,'html.parser')

  # Find the div section that is the parent of all paragraphs
  div = soup.find_all('div', attrs={'class':div_class})

  # Get the text from paragraphs
  extracted_text = []
  for div in div:
      paragraphs = div.find_all('p')
      for paragraph in paragraphs:
          extracted_text.append(paragraph.get_text(strip=True))  # Remove leading/trailing whitespace

  # Splitting the text into sentences, remove the stopwords and punctuations, and save the cleaned version in a list
  sentences = []
  for text in extracted_text:
    sentence = sent_tokenize(text)
    for item in sentence:
      # Convert to lowercase
      text_lowercase = item.lower()
      # Remove punctuation
      text_without_punctuation = re.sub(r"[^\w\s]", "", text_lowercase)
      # Remove stopwords and stem words
      tokens = word_tokenize(text_without_punctuation)
      new_tokens = []
      for word in tokens:
        if word.isnumeric():
          word = num2words(word)
          new_tokens.append(lemmatizer.lemmatize(word))
          continue
        elif word not in stop_words:
          new_tokens.append(lemmatizer.lemmatize(word))
          continue
      # Join tokens back into a string
      cleaned_text = " ".join(new_tokens)
      sentences.append(cleaned_text)

  return sentences

def clean(list):    # For websites that don't allow us to do the web scrape
  cleaned = []
  for i in list:
    sentence = sent_tokenize(i)
    for item in sentence:
      # Convert to lowercase
      text_lowercase = item.lower()
      # Remove punctuation
      text_without_punctuation = re.sub(r"[^\w\s]", "", text_lowercase)
      # Remove stopwords and stem words
      tokens = word_tokenize(text_without_punctuation)
      new_tokens = []
      for word in tokens:
        if word.isnumeric():
          word = num2words(word)
          new_tokens.append(lemmatizer.lemmatize(word))
          continue
        elif word not in stop_words:
          new_tokens.append(lemmatizer.lemmatize(word))
          continue
      # Join tokens back into a string
      cleaned_text = " ".join(new_tokens)
      cleaned.append(cleaned_text)
  return cleaned

website1 = 'https://thinkml.ai/how-artificial-intelligence-is-changing-ecommerce/'
class1 = 'inner'
text1 = scrape_clean(website1, class1)
sentences.extend(text1)
for i in text1:
  print(i)

website2 = 'https://www.websitebuilderexpert.com/grow-online/ai-in-ecommerce/'
class2 = 'col-sm-12 wpb_wrapper'
text2 = scrape_clean(website2, class2)
sentences.extend(text2)
print(text2)

website3 = 'https://www.mgt-commerce.com/blog/ai-in-ecommerce/'
class3 = 'markdown-content'
text3 = scrape_clean(website3, class3)
sentences.extend(text3)
print(text3)

website4 = 'https://creatuity.com/insights/the-impact-of-artificial-intelligence-on-ecommerce'
class4 = 'content'
text4 = scrape_clean(website4, class4)
sentences.extend(text4)
print(text4)

website5 = 'https://www.techradar.com/opinion/how-ai-will-impact-ecommerce-in-2023'
class5 = 'wcp-item-content'
text5 = scrape_clean(website5, class5)
sentences.extend(text5)
print(text5)

website6 = 'https://pixelplex.io/blog/artificial-intelligence-in-ecommerce/'
class6 = 'main-content'
text6 = scrape_clean(website6, class6)
sentences.extend(text6)
print(text6)

website7 = 'https://www.shopify.com/blog/ai-ecommerce'
class7 = 'col-span-4 xs:col-span-12 md:col-span-8 lg:col-span-6 col-start-1'
text7 = scrape_clean(website7, class7)
sentences.extend(text7)
print(text7)

website8 = 'https://www.app0.io/blog/ai-in-ecommerce'
class8 = 'blog-rich-text w-richtext'
text8 = scrape_clean(website8, class8)
sentences.extend(text8)
print(text8)

website9 = 'https://builtin.com/artificial-intelligence/ai-retail-ecommerce-tech'
class9 = 'node--content'
text9 = scrape_clean(website9, class9)
sentences.extend(text9)
print(text9)

# Texts that can't be scraped from website
# https://www.upwork.com/resources/ai-in-ecommerce
# https://machalliance.org/content-hub/how-ai-is-changing-the-e-commerce-industry
# https://www.webretailer.com/ai-retail/ai-in-ecommerce-explained/
# https://www.hostinger.com/tutorials/ai-in-ecommerce
# https://gepard.io/insights-trends/artificial-intelligence-in-ecommerce

not_scraped = ['Artificial Intelligence (AI) is proving to be a game-changing force in e-commerce. It’s transforming how businesses operate and interact with customers—offering unique insights into consumer behavior, helping automate tasks, and improving the shopping experience.', 'AI is playing an increasingly important role in the e-commerce industry, giving companies greater abilities to analyze data and offer a better customer experience.',
               'AI is helping improve customer satisfaction by offering a way to personalize product recommendations. Through data analysis, AI applications look at the company customer data—such as their purchase history and current store activity—and analyze their preferences. With that data, stores can offer personalized recommendations through email, product pages, and add-on recommendations.', 'This proactive approach to inventory management will improve the overall efficiency of a company’s supply chain—leading to more profit and happier customers.',
               'AI helps online stores stay safe by helping identify fraud and stopping it from happening. With a reported 2.4 million fraud complaints in 2022, fraud is still common. Companies try to drive this number down by assessing financial transactions to identify anomalies that indicate fraud.', 'AI can help handle many tasks—such as offering loyalty discounts to customers, providing customer support to people who need help, managing a sales pipeline, handling data entry,  optimizing campaigns with AI marketing, and other tasks.',
               'Looking back at 2023, it has been a huge year for Artificial Intelligence (AI) with the launch of generative pre-trained transformers such as ChatGPT developed by OpenAI, Jasper AI, Adobe Firefly, and many other similar inventions. These tools were welcomed with excitement as well as uncertainty, as any new technology brings a bit of unknown.', 'From what we know so far, AI has changed the way we work across several industries, including e-commerce and provided new and exciting opportunities to make our lives easier and our jobs more efficient. In 2023, around 35% of all companies across all industries are using AI in their business. The highest adoption of AI includes: financial services, healthcare, retail and manufacturing. AI is a technology that will grow in strength in the years to come. According to Gartners, Gartner Top 10 Strategic Technology Trends for 2024: By 2026, generative AI will significantly alter 70% of the design and development effort for new web applications and mobile apps.',
               'All of these strategies are a game changer for companies in making data-driven decisions, reducing operating costs, improving efficiency, and, as a result, staying competitive in a rapidly evolving industry.', 'Product recommendations based solely on the customer segment or other generic assumption is a sure way to lose a sale! With all the data available to marketers these days, personalized product recommendations are here to stay. AI changed the way products are being promoted to customers, and to my delight — dynamic, real-time suggestions based on customer behavior and personal preferences is what drives sales and customer satisfaction (my unique fashion style is finally getting noticed by fashion companies!). For instance, Amazon’s recommendation uses AI to analyze browsing and purchasing history before making any product suggestions tailored to the buyer’s interest and intent.',
               'AI-powered voice recognition has redefined the shopping experience in e-commerce, making it even more intuitive and convenient for customers. Shopping while driving? It’s possible now with voice assistants such as Amazon’s Alexa or Google Assistant that offer consumers a hands-free and user-friendly interaction with their favorite brands. This might be an extreme example, but on a serious note, these technologies have helped immensely people who have certain disabilities and might struggle or find it impossible to work with a mouse or keyboard enabling a whole new world of possibilities.', 'On the other hand, image recognition empowered shoppers with another way of product recommendation by uploading a photo of items they want to purchase. So far, the best application of this feature was adopted by Pinterest’s “Shop the Look” which enables users to click on the “pinned” image to find similar ones available in stores. In addition, ASOS, the UK’s biggest online fashion retailer, launched “Style Match,” which allows users to snap a photo of an outfit and explore similar outfits from their inventory.',
               'Optimizing supply chains while reducing waste and boosting efficiency — here are only a few ways AI technologies improve inventory management. No one likes shopping in a store only to find out that your size is no longer available. Well, with AI this should never happen as the algorithm can predict demand for various products (successfully launched by Amazon). But also, Walmart has taken this to the next level, while using AI for real-time inventory tracking, helping store managers to restock items before they run low.', 'Are these technologies only available to big players? Luckily, with Shopifys AI-driven inventory management tools, small businesses can follow this trend and ensure they meet customer expectations, reduce waste and optimize inventory.',
               'Have you ever found yourself searching for affordable flights on desired dates to eventually book the exact same flight 20% more expensive a few days later? Or trying to book an Uber and getting it one minute later for a higher price? Well, that’s now possible for e-commerce businesses (let’s hope for a rather downward trend!). Online retailers can effectively adopt AI for real-time pricing strategies ensuring they remain competitive and maximize profitability. For example, Media Markt adopted dynamic pricing offering the same TV at different prices during different times a day, however decided to partially refund customers up to two weeks after the purchase if the price was lower than when they bought the product.', 'Another space within e-commerce, which has not been omitted by AI is product information management (PIM). PIM solutions are handling massive amounts of data, hence the adoption of AI has been long awaited to bring some significant optimization across all channels of data management. Through machine learning algorithms, AI improves data quality by identifying and correcting errors, inconsistencies, and duplicates in product information.',
               'Additionally, AI-driven PIM solutions streamline data enrichment processes by automatically tagging and classifying products based on attributes. Intelligent automation reduces manual efforts in updating product details, ensuring real-time accuracy. Predictive analytics within AI-powered PIM systems help businesses anticipate market trends and customer preferences, facilitating data-driven decision-making.', 'AI can significantly benefit the MACH (Microservices, API-first, Cloud-native, and Headless) architecture by enhancing its key principles. In the context of microservices, AI can optimize and automate service orchestration, ensuring efficient communication and collaboration among microservices. API-first design can leverage AI to enhance API management, ensuring seamless integration and data exchange. Cloud-native deployments benefit from AI-driven auto-scaling, resource optimization, and predictive maintenance, improving overall performance and cost efficiency. Headless architecture, with its focus on decoupled front-end and back-end, can leverage AI for personalized content delivery and user experience optimization. Moreover, AI can analyze vast datasets generated by MACH systems to derive valuable insights, enabling data-driven decision-making. Overall, AI complements and enhances each aspect of the MACH architecture, fostering agility, scalability, and intelligence in modern digital ecosystems.',
               'Despite the benefits, the AI raises valid concerns. Privacy becomes a paramount issue as these technologies gather and analyze vast amounts of user data. The absence of human interaction in customer service may lead to a less personalized experience, impacting customer satisfaction. Automation, while efficient, poses a risk to employment, with certain tasks susceptible to job displacement. As we navigate this tech-driven era, addressing these drawbacks becomes imperative to foster a harmonious coexistence between innovation and societal well-being.', 'In the dynamic landscape of e-commerce, AI emerges as a double-edged sword, offering unprecedented advantages while wielding potential pitfalls. On the bright side, it catapults efficiency, personalization, and user experience to new heights. However, shadowing this brilliance are concerns like privacy issues, the risk of job displacement, and the subtle erosion of the human touch in customer interactions. Striking a balance between innovation and ethical considerations is the key to navigating this digital frontier. As we ride the e-commerce wave, lets ensure that AIs role is one of an invaluable assistant, not an accidental antagonist.',
               'AI in eCommerce is about leveraging technology to automate and optimize processes. The objective is to improve customer engagement while increasing revenue. By channeling the strengths of AI, you can streamline functions, boost efficiency, and provide a more tailored and smoother shopping experience for customers.', 'AI in eCommerce is about leveraging technology to automate and optimize processes. The objective is to improve customer engagement while increasing revenue. By channeling the strengths of AI, you can streamline functions, boost efficiency, and provide a more tailored and smoother shopping experience for customers.',
               'In eCommerce, AI helps business owners streamline their operations, create profiles of their customers based on shopping patterns, and enhance their digital assets to improve buyer experience.', 'AI is now omnipresent in eCommerce business operations. Entrepreneurs include it in their inventory, fulfillment, marketing, customer service, and HR strategies.', 'The AI use cases in eCommerce are constantly expanding, and businesses that embrace it are guaranteed a competitive edge. Big data is the major contribution of AI to eCommerce. Its ability to process vast amounts of information fuels wise business decisions encompassing the entire online store operations.',
               'By analyzing the wealth of consumer data on buying behavior, preferences, and price sensitivity, AI algorithms can suggest relevant products to shoppers. These personalized product recommendations increase the likelihood of a purchase. Additionally, AI-powered virtual shopping assistants can provide buyers with customized offers and a more interactive shopping experience.', 'Automated checkouts, on the other hand, facilitate a faster purchase journey with zero human error, less number of clicks, and simpler checkout forms. This also benefits online store owners as seamless checkouts decrease abandoned cart incidents.',
               'AI is transforming customer service with automated chatbots that never sleep, can answer queries 24/7, and resolve issues instantly. That means human customer service representatives can provide more high-level assistance to buyers with more complicated issues. Meanwhile, customers save time when their concerns are addressed immediately. Employees can focus on other important tasks by reducing time spent on repetitive and basic tasks.', 'Inventory management and demand forecasting are two other areas where AI benefits enterprises. It makes supply chains work more efficiently toward meeting accurate expectations. Predictive analytics allow businesses to accurately forecast demand, avoid stockouts, and prevent wastage based not only on past data but also on future events.', 'On the other hand, warehouses can boost productivity through computer vision, a product recognition AI technology that enables workers to locate items precisely.',
               'AI also empowers businesses to be dynamic with pricing strategies, ensuring they are competitive in the market without sacrificing profitability.', 'AI enables more tailored advertisements to individual customers based on their browsing and purchasing history. Consequently, businesses can shift from traditional ads that cast a wide net to AI-inspired ones which target individuals most likely to buy. This, in turn, translates to reduced expenses on marketing and advertising efforts.', 'Analyzing data is one of the strengths of AI, and it is extremely helpful in identifying questionable actions on eCommerce platforms. Each transaction shows a risk score on AI-based systems to flag out-of-the-ordinary purchasing patterns. Plus, AI technology makes identity recognition more accurate using biometric and document verification.',
               'Some human roles may become obsolete as businesses rely on automation and AI algorithms in more processes.', 'There is no other way for AI to provide customized services to shoppers but to access their personal information. However, this raises concerns about how that data is stored and, more importantly, protected.', 'If not carefully designed and monitored, AI systems may unintentionally amplify existing biases and unfairly target or exclude some groups of buyers. For example, a Statista survey found that more than 40% of online shoppers of the Baby Boomers generation are not comfortable with using AI for personalization. Businesses need to be aware of these potential negative impacts and take steps to avoid such risks in their AI applications.',
               'Artificial intelligence helps eCommerce businesses improve their targeted advertising. With AI, collecting and analyzing real-time consumer data like online browsing habits and previous purchases is easier and more cost-effective.',
               'Offering a personalized customer experience is key to improving customer satisfaction. With AI technology, you can predict behavior based on customer interactions and purchase histories.',
               'Personalization also helps increase customer retention. You can build lasting impressions and solid relationships by acknowledging customers’ pain points and preferences.',
               'Using AI in eCommerce lets you automate repetitive tasks, optimize workflows, and analyze large amounts of business data quickly. You can reduce the time and human resources needed by making your eCommerce business work more efficiently.',
               'Besides improving operational efficiency, AI integration in eCommerce can detect fraud, predict market demand, and optimize energy consumption. These practices reduce operating expenses and save you money in the long run.',
               'Anyone who knows how to start an online business understands how important it is to stand out, especially when there are 7.1 million online retailers as competition. AI eCommerce solutions can offer competitive advantages. For instance, integrating AI chatbots into your support channel increases your responses’ speed and accuracy. As a result, you will offer a better customer experience than other online retailers.',
               'One of the most popular branches of artificial intelligence is Natural Language Processing (NLP). NLP allows computers to understand human language in spoken and written forms. In a data analysis process, the quality of generated information improves the more data it feeds on. However, big data comes with data privacy concerns. An AI eCommerce platform managing huge amounts of data may risk data leakage and jeopardize customers’ personal information. To maintain customer trust, eCommerce business owners must disclose what data their AI engine can access and for what purpose. Prioritizing cybersecurity strategies is also a must.',
               'The implementation of artificial intelligence in eCommerce comes with ethical issues. For instance, feeding biased data into AI algorithms results in unfair outcomes for certain groups of people. If used by the wrong people, artificial intelligence can become a tool for discrimination. Transparency must be present in AI development and implementation to ensure an accountable and fair automated decision-making process. Using unbiased data to train AI software will help you get unbiased results.',
               'AI systems need dedicated infrastructures with advanced processing abilities to process big data. In reality, many companies don’t have the resources to invest in the infrastructure and tools required to run AI systems. You can outsource AI-powered tools, but they will cost you hundreds of thousands of dollars annually. Many companies also don’t have enough quality data to train their machine-learning algorithms, resulting in biased outcomes. For this reason, understanding how artificial intelligence works and what resources it requires is vital for a successful implementation.',
               'The concept of artificial intelligence in eCommerce is still relatively new. Therefore, hiring experts who know how to leverage AI algorithms for quality results is challenging. Business owners should train their employees to use AI, specifically machine learning, in their workflow. As employees will later be operators, they must understand how these technologies can benefit their work.',
               'The insights and automation provided by artificial intelligence allow retail businesses to create a consistent, seamless customer experience across online and offline stores.',
               'eCommerce retailers can leverage AI systems for supply chain optimization. Customer demand forecasting, product restock planning, and bottleneck elimination are several improvements AI can make to an eCommerce business’ supply chain management. Meanwhile, AI robots support warehouse management by streamlining order processing and reducing human error. By increasing warehouse efficiency, artificial intelligence helps reduce carbon footprint and inventory discrepancy.',
               'Integrating AI models into fraud prevention measures allows real-time monitoring and pattern analysis. With machine learning, eCommerce companies can scan real-time online sales for suspicious customer behavior and purchase history. Reducing the risk of fraud saves your eCommerce business money and gains customer trust for your brand.',
               'Besides helping with customer acquisition, predictive analytics also benefits your remarketing efforts. You can target online shoppers who have visited your eCommerce site with personalized ads to influence their decision-making process. It’s also effective in reducing cart abandonment rates.',
               'The main applications of NLP in eCommerce are voice-activated payments, virtual conversation, and voice searches.',
               'Computer vision allows face detection and identification when it comes to artificial intelligence in eCommerce.',
               'A smart recommendation engine for online shops works based on user behavior and offers users products they are looking for. The algorithm analyzes the user behavior patterns such as frequent product views, considerations, and purchases. Based on the analyses, the most relevant product suggestions are displayed.',
               'Virtual dressing rooms are a type of software that helps consumers digitally try on clothing. The item can be placed over a live image of the buyer using artificial intelligence technology and is essentially acting as an enhanced shopping assistant.',
               'Supply chain planning: AI algorithms are capable of processing and analyzing enormously large data volumes, helping retail businesses detect logistical disruptions. Research done by IBM found that 40% of companies that participated in the survey resolve supply chain challenges using AI.',
               'Customer research: AI allows for cutting costs in performing market research and doing it more efficiently. Machine learning software is already capable of performing tasks such as finding survey respondents, analyzing open-ended replies (unstructured data), and determining what follow-up questions to ask.',
               'Shoppers mood tracking: AI-powered eCommerce technologies can track and detect certain consumer moods and trends, helping online shops to keep a more accurate product stock. The Very Group successfully implemented AI mood tracking technology in their machine-learning chatbot. It detects customers’ tone in messages and adjusts replies based on that information. The AI system eventually became the most used customer support channel of the company.',
               ]
cleaned = clean(not_scraped)
sentences.extend(cleaned)
print(cleaned)

for i in sentences:
  print(f'{i}\n')

# Use Vader library to get the polarity of the sentence
def getPolarity(text):
    polarity = SentimentIntensityAnalyzer().polarity_scores(text)
    if polarity['compound'] > 0:
      sentiment = 'postive'
    elif polarity['compound'] < 0:
      sentiment = 'negative'
    else:
      sentiment = 'neutral'
    return sentiment,polarity

data = []  # List to store dictionaries
for sentence in sentences:
  sentiment, polarity = getPolarity(sentence)
  new_item = {'sentence' : sentence, 'sentiment' : sentiment, 'category' : 'E-Commerce'}
  data.append(new_item)

df = pd.DataFrame(data)

df.to_csv('E-Commerce data (no numbers) - Vader ver.csv', index=False)